# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/grpc/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pp/grpc/user.proto\x12\x04user\"\"\n\x11GetProfileRequest\x12\r\n\x05token\x18\x01 \x01(\t\"%\n\x12GetByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x88\x01\n\x0cProfileReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\x0b\n\x03\x62io\x18\x05 \x01(\t\x12\x12\n\navatar_url\x18\x06 \x01(\t\x12\x12\n\nis_private\x18\x07 \x01(\x08\x32\x8c\x01\n\x0bUserService\x12\x39\n\nGetProfile\x12\x17.user.GetProfileRequest\x1a\x12.user.ProfileReply\x12\x42\n\x12GetProfileByUserId\x12\x18.user.GetByUserIdRequest\x1a\x12.user.ProfileReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROFILEREQUEST']._serialized_start=29
  _globals['_GETPROFILEREQUEST']._serialized_end=63
  _globals['_GETBYUSERIDREQUEST']._serialized_start=65
  _globals['_GETBYUSERIDREQUEST']._serialized_end=102
  _globals['_PROFILEREPLY']._serialized_start=105
  _globals['_PROFILEREPLY']._serialized_end=241
  _globals['_USERSERVICE']._serialized_start=244
  _globals['_USERSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
