# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/grpc/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pp/grpc/auth.proto\x12\x04\x61uth\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\xbd\x01\n\x0b\x41uthService\x12\x39\n\x0cRegisterUser\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\x12\x33\n\tLoginUser\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12>\n\rValidateToken\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=29
  _globals['_REGISTERREQUEST']._serialized_end=97
  _globals['_LOGINREQUEST']._serialized_start=99
  _globals['_LOGINREQUEST']._serialized_end=149
  _globals['_AUTHRESPONSE']._serialized_start=151
  _globals['_AUTHRESPONSE']._serialized_end=207
  _globals['_VALIDATEREQUEST']._serialized_start=209
  _globals['_VALIDATEREQUEST']._serialized_end=241
  _globals['_VALIDATERESPONSE']._serialized_start=243
  _globals['_VALIDATERESPONSE']._serialized_end=293
  _globals['_AUTHSERVICE']._serialized_start=296
  _globals['_AUTHSERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
