version: '3.9'
services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: .
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+asyncpg://auth_user:password@auth-db:5432/auth_db
    volumes:
      - .:/app
    depends_on:
      - auth-db

volumes:
  auth_db_data: